DROP TABLE IF EXISTS TRADE_STORE;

CREATE TABLE TRADE_STORE (
    TRADE_ID VARCHAR(50) NOT NULL,
    VERSION INT NOT NULL,
    CP_ID VARCHAR(50) NOT NULL,
    BOOK_ID VARCHAR(50) NOT NULL,
    MATURITY_DATE DATE NOT NULL,
    CREATE_DATE DATE NOT NULL,
    EXPIRED CHAR(1) NOT NULL DEFAULT 'N',
    PRIMARY KEY(TRADE_ID, VERSION)
);